spring:
  application:
    name: wms
  mail:
    host: smtp.qq.com
    port: 587
    username: "2640052921@qq.com"
    password: "bwombgladdzudich"

    properties:
      "mail.smtp.ssl.enable": false
    default-encoding: utf-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sa@123
    url: jdbc:mysql://127.0.0.1:3306/wms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
server:
  port: 8081
  servlet:
    context-path: /wms
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  global-config:
#    field-strategy: 0
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
